# TinyTS Docker Image

ARG UBUNTU_VER=18.04
ARG CONDA_VER=latest
ARG OS_TYPE=x86_64
ARG PY_VER=3.8.11
ARG TF_VER=2.5.0

FROM ubuntu:20.04

ADD docker_setup /TinyTS/docker/docker_setup/

WORKDIR /TinyTS/docker/docker_setup

ENV PATH=/TinyTS/docker/miniconda/bin:${PATH}

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata

RUN apt install -y curl wget gcc g++ gdb git mercurial libusb-1.0-0-dev usbutils vim udev cmake make flatbuffers-compiler

# Install Conda
RUN    [ "$(uname -m)" = "aarch64" ] && \
        wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh" -O conda_install.sh || \
        wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O conda_install.sh \
    && bash conda_install.sh -b -p /TinyTS/docker/miniconda

# Configure Conda
RUN    conda init bash \
    && conda update -y conda 

# Create abd Setup venv
RUN    conda create -n TinyTS python=3.7 && \
        echo "conda activate TinyTS" >> ~/.bashrc

# Install mbed toolchain: Install & Configure Mbed-cli
RUN  /TinyTS/docker/miniconda/envs/TinyTS/bin/python -m pip install mbed-cli \
    && /TinyTS/docker/miniconda/envs/TinyTS/bin/python -m pip install -r mbedos_requirements.txt \
    && /TinyTS/docker/miniconda/envs/TinyTS/bin/python -m mbed config -G MBED_GCC_ARM_PATH /TinyTS/docker/gcc-arm-none-eabi-10.3-2021.10/bin/ \
    && /TinyTS/docker/miniconda/envs/TinyTS/bin/python -m mbed config -G TOOLCHAIN GCC_ARM \
    && /TinyTS/docker/miniconda/envs/TinyTS/bin/python -m mbed config -G TARGET detect

# Ref:https://github.com/ARMmbed/mbed-os/blob/72f27cee92a4bdafa30513f732e007ba635dc93f/docker_images/mbed-os-env/Dockerfile#L67
# Install arm-none-eabi-gcc
RUN set -x \
    && [ "$(uname -m)" = "aarch64" ] && \
        TARBALL="gcc-arm-none-eabi-10.3-2021.07-aarch64-linux.tar.bz2" || \
        TARBALL="gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2" \
    && wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/${TARBALL} \
    && tar -xjf ${TARBALL} -C /TinyTS/docker/ \
    && rm ${TARBALL} \
    && : # last line
# Configure environment variables
ENV MBED_GCC_ARM_PATH=/TinyTS/docker/gcc-arm-none-eabi-10.3-2021.07/bin/
ENV PATH="${PATH}:${MBED_GCC_ARM_PATH}"

RUN rm -rf /TinyTS/docker_setup

WORKDIR /TinyTS
